// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkC3uGj0wet9ihXSO8vnSNQHfnffRaVo',
    appId: '1:388539381161:web:edd5107748a84614ed00b8',
    messagingSenderId: '388539381161',
    projectId: 'nexus-gateway-cca4c',
    authDomain: 'nexus-gateway-cca4c.firebaseapp.com',
    storageBucket: 'nexus-gateway-cca4c.firebasestorage.app',
    measurementId: 'G-58WP0V43MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGOtsxQl3HwCOz5rHrpVP2gB6iTuCp-5Y',
    appId: '1:388539381161:android:bc6a5621264ad473ed00b8',
    messagingSenderId: '388539381161',
    projectId: 'nexus-gateway-cca4c',
    storageBucket: 'nexus-gateway-cca4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OroBtGbKNLQV_u0MGS7xGQWwxy6qfSw',
    appId: '1:388539381161:ios:a591793ed7b42cb7ed00b8',
    messagingSenderId: '388539381161',
    projectId: 'nexus-gateway-cca4c',
    storageBucket: 'nexus-gateway-cca4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterClient',
  );
}
